name: PHPUnit

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: hyperf/hyperf:${{ matrix.hyperf-version }}
    strategy:
      matrix:
        hyperf-version:
          - "8.1-alpine-v3.19-swoole"
          - "8.2-alpine-v3.22-swoole"
          - "8.3-alpine-v3.23-swoole"
      fail-fast: false
      max-parallel: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          pwd
          ls -al
          php -v
          php -m
          php --ri swoole
          composer -V

      - name: Install Dependencies
        run: |
          composer update -o --no-scripts
          composer info

      - name: Static Analysis
        run: composer analyse

      - name: Run Tests
        run: composer test
